### ISSUE TITLE
Tags are incomplete in projects using Komodo package

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#67]
When you use Komodo as a package at the moment, the tag list is incomplete. I suspect this is because Unity detects which prefabs have tag strings on them and auto-generates those tags.

Example (MenuUI.prefab): 

```

GameObject:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 7837119552983968088}
  - component: {fileID: 7946481211550140238}
  - component: {fileID: 7946847445959112422}
  m_Layer: 5
  m_Name: List
  m_TagString: UIInteractable
                       ^
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!224 &7837119552983968088
```

So in theory we could add a prefab to gelic-idealab/komodo-unity to force projects that use Komodo to generate those tags. As in, the prefab looks like this: 

```
TagGenerator
    Interactable
    UIInteractable
    UserIgnore
    HandL
    HandR
    Hands
    ...
```

And if you click on each item, it is tagged with its own name.

But it might be better to write up a tag manager and add Komodo tags to a user's project. We should "namespace" the tags if we can too -- UIInteractable -> KomodoUIInteractable, or something like that. 

https://answers.unity.com/questions/33597/is-it-possible-to-create-a-tag-programmatically.html
